

# run-as: ecommerce front-end microservice.

version: 0.2

env:
  variables:
    MY_AWS_REGION: "us-east-1"
        
phases:
  install:
    runtime-versions: 
          nodejs: 12
    commands:
      - echo "Hey welcome to AWS codebuild. My name is $name.Testing codebuild automation"
      - echo "Running on ${MY_AWS_REGION}"
      - echo "Start installation process"
      - echo "Installation Process Completed"
      - echo "My code build id is $CODEBUILD_BUILD_ID"
    
  pre_build:
    commands:
      - echo "This is the start of Pre-Build Phase"
      - echo "Pre-Build Phase is now completed"

  build:
    commands:
      - echo "This is the start of the build phase"
      - echo "The Build phase is now complete"
      - echo "Run Basic check whether website is ready for us"
      - grep -Fq "Shop" front-end/files/public/index.html
      - echo "Test was successful. So cool"

  post_build:
    commands:
      - echo "we are cuurently on post_build phase"
      - echo "post_build phase activity is completed. Moving next to artifacts"

artifacts:
  files:
    -  '**/*'  #buildspec.yml